### ISSUE TITLE
Support for newer kubernetes versions

### ISSUE THREAD

**Issue by nazarkulyk** [hansehe/jaeger-all-in-one#5]
I tested your helm with current minikube and k8s and cant install chart.

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "jaeger-all-in-one" namespace: "default" from "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
ensure CRDs are installed first`

So ingress template should be changed to use "networking.k8s.io/v1" for higher kubernetes versions.

```bash
minikube version
# minikube version: v1.26.0

kubectl get node
# NAME       STATUS   ROLES           AGE   VERSION
# minikube   Ready    control-plane   12d   v1.24.1
```

**Comment by hansehe** [comment]
Thanks a lot! I forgot about this upgrade and the newest version 0.1.7 should fix the issue.
