### ISSUE TITLE
Metadata kubernetes version passing as number values instead of string value

### ISSUE THREAD

**Issue by vijaykumarv7** [hansehe/jaeger-all-in-one#8]
Hello,

When I tried to use your helm chart it's failing because of metadat has kubernetes version which is bieng getting as number which is not acceptable in kubernetes manifest.

Could you please create a fix for the same or provide solutions to use it.

**Comment by hansehe** [comment]
Hi, and thanks for making me aware of this.

Fixed it now, and published a new helm chart (0.1.10), and tell me if there are any other problems.
