### ISSUE TITLE
OTLP Ports

### ISSUE THREAD

**Issue by suhanth94** [hansehe/jaeger-all-in-one#9]
@hansehe Can you please add OTLP ports (4317 and 4318) in the configuration of https://github.com/hansehe/jaeger-all-in-one/blob/master/helm/jaeger-all-in-one/templates/service.yaml and release a new version?

**Comment by hansehe** [comment]
Thanks for the update, just briefed through the documentation and upgraded to version 1.47 at the same time.
Enable the 'enableHttpOpenTelemetryCollector' value (see values.yaml) to activate the opentelemetry endpoints.
